version: '3'
services: 
  db:
    restart: always
    image: postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "8001:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  tracing:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
  app:
    build: .
    restart: always
    environment:
      - DBHOST=db
      - USER=postgres
      - PASSWORD=postgres
      - DBNAME=postgres
      - DBPORT=5432
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata:
